{{- range $name, $spec := .Values.configMaps }}
{{- if not (and (hasKey $spec "enabled") (not $spec.enabled)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "tpl.metadata" (dict "context" $ "name" $name "labels" $spec.labels "annotations" $spec.annotations) | nindent 2 }}
{{- with $spec.data }}
data: {{ toYaml . | nindent 2 }}
{{- end }}
{{- with $spec.binaryData }}
binaryData: {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
