{{- $mergedValues := mustMergeOverwrite (dict) .Values.global .Values }}
{{- if and (eq $mergedValues.kind "Deployment") $mergedValues.autoscaling.enabled }}
---
  {{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tpl.fullname" . }}
  labels:
  {{- include "tpl.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tpl.fullname" . }}
  minReplicas: {{ $mergedValues.autoscaling.minReplicas }}
  maxReplicas: {{ $mergedValues.autoscaling.maxReplicas }}
  {{- with $mergedValues.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $mergedValues.autoscaling.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}