{{- range $name, $spec := .Values.podMonitors }}
{{- if not (and (hasKey $spec "enabled") (not $spec.enabled)) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  {{- include "tpl.metadata" (dict "context" $ "name" $name "labels" $spec.labels "annotations" $spec.annotations) | nindent 2 }}
spec:
  {{- with $spec.selector }}
  selector: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $spec.namespaceSelector }}
  namespaceSelector: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $spec.podMetricsEndpoints }}
  podMetricsEndpoints: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
