{{- range $name, $spec := .Values.secrets }}
{{- if not (and (hasKey $spec "enabled") (not $spec.enabled)) }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- include "tpl.metadata" (dict "context" $ "name" $name "labels" $spec.labels "annotations" $spec.annotations) | nindent 2 }}
type: {{ $spec.type | default "Opaque" }}
{{- with $spec.data }}
data: {{ toYaml . | nindent 2 }}
{{- end }}
{{- with $spec.stringData }}
stringData: {{ toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
