{{- $mergedValues := mustMergeOverwrite (dict) .Values.global .Values }}
{{- if $mergedValues.secrets }}
  {{- range $secret_name, $secret_spec := $mergedValues.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
    {{- with $secret_spec.labels }}
  labels:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $secret_spec.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $secret_spec.type }}
type: {{ . }}
    {{- end }}
    {{- with $secret_spec.stringData }}
stringData:
      {{- include "tpl.render" (list $ . (toYaml .)) | nindent 2 }}
    {{- end }}
    {{- with $secret_spec.data }}
data:
      {{- include "tpl.render" (list $ . (toYaml .)) | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}