{{- range $name, $spec := .Values.serviceAccounts }}
{{- if not (and (hasKey $spec "enabled") (not $spec.enabled)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "tpl.metadata" (dict "context" $ "name" $name "labels" $spec.labels "annotations" $spec.annotations) | nindent 2 }}
{{- if kindIs "bool" $spec.automountServiceAccountToken }}
automountServiceAccountToken: {{ $spec.automountServiceAccountToken }}
{{- end }}
{{- end }}
{{- end }}
