{{- if and (eq .Values.kind "Deployment") .Values.autoscaling.enabled }}
---
  {{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tpl.fullname" . }}
  labels:
  {{- include "tpl.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tpl.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.autoscaling.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
