apiVersion: v2
name: tpl
description: Chart for templating kubernetes resources using values. Can be used as single dependency, as multiple dependencies, as is. See examples for use cases
type: application
version: 0.12.0
appVersion: 0.12.0
